import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Azoux Learning NextJS</title>
      </head>
      <body>
        <nav className="w-full h-10 bg-slate-400 items-center flex content-between text-2xl">
          <h1 className="p-2 underline hover:bg-white hover:transition-all">
            <Link href="/">Home</Link>
          </h1>
          <h1 className="p-2 underline hover:bg-white hover:transition-all">Error</h1>
          <h1 className="p-2 underline hover:bg-white hover:transition-all">
            <Link href="/todo">Todo</Link>
          </h1>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
